// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pTPBBsFpDxNXZWEGB1hTFr
// Component: bUJeyBWdrf
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_anais.module.css"; // plasmic-import: pTPBBsFpDxNXZWEGB1hTFr/projectcss
import * as sty from "./PlasmicMoreButton.module.css"; // plasmic-import: bUJeyBWdrf/css

export const PlasmicMoreButton__VariantProps = new Array();

export const PlasmicMoreButton__ArgProps = new Array();

function PlasmicMoreButton__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.button,
        defaultcss.__wab_text,
        projectcss.root_reset,
        sty.root
      )}
    >
      {"Voir Plus"}
    </button>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMoreButton__ArgProps,
      internalVariantPropNames: PlasmicMoreButton__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicMoreButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMoreButton";
  } else {
    func.displayName = `PlasmicMoreButton.${nodeName}`;
  }
  return func;
}

export const PlasmicMoreButton = Object.assign(
  // Top-level PlasmicMoreButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicMoreButton
    internalVariantProps: PlasmicMoreButton__VariantProps,
    internalArgProps: PlasmicMoreButton__ArgProps
  }
);

export default PlasmicMoreButton;
/* prettier-ignore-end */
