// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pTPBBsFpDxNXZWEGB1hTFr
// Component: oABxe4ux2c
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_anais.module.css"; // plasmic-import: pTPBBsFpDxNXZWEGB1hTFr/projectcss
import * as sty from "./PlasmicTeamMemberCard.module.css"; // plasmic-import: oABxe4ux2c/css

export const PlasmicTeamMemberCard__VariantProps = new Array();

export const PlasmicTeamMemberCard__ArgProps = new Array("slot", "children");

function PlasmicTeamMemberCard__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box__epQhj)}>
        {p.renderPlasmicSlot({
          defaultContents: (
            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__u19De)}
              role={"img"}
            />
          ),

          value: args.slot
        })}
      </div>

      <div className={classNames(defaultcss.all, sty.box__gqXx)}>
        {p.renderPlasmicSlot({
          defaultContents: "Enter some text",
          value: args.children,
          className: classNames(sty.slotChildren)
        })}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTeamMemberCard__ArgProps,
      internalVariantPropNames: PlasmicTeamMemberCard__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicTeamMemberCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTeamMemberCard";
  } else {
    func.displayName = `PlasmicTeamMemberCard.${nodeName}`;
  }
  return func;
}

export const PlasmicTeamMemberCard = Object.assign(
  // Top-level PlasmicTeamMemberCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTeamMemberCard
    internalVariantProps: PlasmicTeamMemberCard__VariantProps,
    internalArgProps: PlasmicTeamMemberCard__ArgProps
  }
);

export default PlasmicTeamMemberCard;
/* prettier-ignore-end */
